--------------------------------------------------------
--  File created - Tuesday-March-31-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "EMPLEADOS"."DEPARTAMENTO" 
   (	"DEPARTAMENTOID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "EMPLEADOS"."EMPLEADO" 
   (	"EMPLEADOID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DEPARTAMENTOID" NUMBER, 
	"PUESTOID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUESTO
--------------------------------------------------------

  CREATE TABLE "EMPLEADOS"."PUESTO" 
   (	"PUESTOID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VW_EMPLEADOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "EMPLEADOS"."VW_EMPLEADOS" ("EMPLEADOID", "NOMBRE", "PUESTOID", "DESCRIPCIONPUESTO", "DEPARTAMENTOID", "DESCRIPCIONDEPARTAMENTO") AS 
  SELECT
        E.EmpleadoID,
        E.Nombre,
        P.PuestoID,
        P.Descripcion       AS DescripcionPuesto,
        D.DepartamentoID,
        D.Descripcion       AS DescripcionDepartamento
    FROM
        EMPLEADO    E
        INNER JOIN PUESTO       P ON E.PuestoID      = P.PuestoID
        INNER JOIN DEPARTAMENTO D ON E.DepartamentoID = D.DepartamentoID
;
REM INSERTING into EMPLEADOS.DEPARTAMENTO
SET DEFINE OFF;
Insert into EMPLEADOS.DEPARTAMENTO (DEPARTAMENTOID,DESCRIPCION) values (1,'Soporte TÈcnico');
Insert into EMPLEADOS.DEPARTAMENTO (DEPARTAMENTOID,DESCRIPCION) values (2,'AdministraciÛn');
Insert into EMPLEADOS.DEPARTAMENTO (DEPARTAMENTOID,DESCRIPCION) values (3,'Compras');
Insert into EMPLEADOS.DEPARTAMENTO (DEPARTAMENTOID,DESCRIPCION) values (4,'Ventas');
Insert into EMPLEADOS.DEPARTAMENTO (DEPARTAMENTOID,DESCRIPCION) values (5,'Recursos Humanos');
REM INSERTING into EMPLEADOS.EMPLEADO
SET DEFINE OFF;
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (25,'Gabriela N√∫√±ez Paredes',2,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (23,'Juan Lopez Martinez',1,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (24,'Diego Valenzuela R√≠os',1,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (26,'H√©ctor Casta√±eda Ibarra',3,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (28,'Armando Cervantes Bravo',5,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (29,'Natalia Fuentes Arriaga',1,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (30,'Oswaldo Pe√±a Guti√©rrez',2,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (31,'Leticia Vargas Montes',3,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (32,'Benjam√≠n Alvarado Cruz',4,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (33,'Daniela Espinoza T√©llez',5,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (34,'Mauricio Delgado Soto',1,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (35,'Alejandra Ramos Villanueva',2,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (36,'Iv√°n Contreras Medina',3,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (37,'Cristina Mendez Aguilar',4,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (1,'Alfredo PÈrez Torres',1,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (2,'Fernando Gonzalez JimÈnez',1,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (3,'Luis Martinez PÈrez',1,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (4,'MarÌa LÛpez GarcÌa',2,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (5,'Carlos RodrÌguez Ruiz',2,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (6,'Ana Torres Mendoza',3,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (7,'Roberto S·nchez DÌaz',3,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (8,'Patricia Flores Vega',4,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (9,'Miguel Herrera Castro',4,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (10,'SofÌa RamÌrez Luna',5,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (41,'Alberto Tenorio Salazar',5,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (42,'Carlos Mendoza Rivera',1,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (43,'Laura S√°nchez Torres',2,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (44,'Roberto Jim√©nez Cruz',3,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (45,'Ana Patricia Morales',1,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (46,'Diego Alejandro Fuentes',4,5);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (47,'Sof√≠a Guadalupe Reyes',2,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (48,'Miguel √?ngel Hern√°ndez',5,1);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (49,'Valentina Castillo Ruiz',3,2);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (50,'Fernando L√≥pez G√≥mez',1,4);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (51,'Isabella Ram√≠rez Vega',4,3);
Insert into EMPLEADOS.EMPLEADO (EMPLEADOID,NOMBRE,DEPARTAMENTOID,PUESTOID) values (52,'Damian Rosas Aguilar',2,2);
REM INSERTING into EMPLEADOS.PUESTO
SET DEFINE OFF;
Insert into EMPLEADOS.PUESTO (PUESTOID,DESCRIPCION) values (1,'Gerente');
Insert into EMPLEADOS.PUESTO (PUESTOID,DESCRIPCION) values (2,'Jefe');
Insert into EMPLEADOS.PUESTO (PUESTOID,DESCRIPCION) values (3,'Supervisor');
Insert into EMPLEADOS.PUESTO (PUESTOID,DESCRIPCION) values (4,'Analista');
Insert into EMPLEADOS.PUESTO (PUESTOID,DESCRIPCION) values (5,'Secretaria');
--------------------------------------------------------
--  DDL for Procedure SP_BUSCAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_BUSCAR_EMPLEADO" (
    p_nombre IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT
            EmpleadoID,
            Nombre,
            PuestoID,
            DescripcionPuesto,
            DepartamentoID,
            DescripcionDepartamento
        FROM VW_EMPLEADOS
        WHERE UPPER(Nombre) LIKE '%' || UPPER(p_nombre) || '%'
        ORDER BY Nombre;
END SP_BUSCAR_EMPLEADO;

/
--------------------------------------------------------
--  DDL for Procedure SP_CONSULTAR_DEPARTAMENTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_CONSULTAR_DEPARTAMENTOS" (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT DepartamentoID, Descripcion
        FROM DEPARTAMENTO
        ORDER BY DepartamentoID;
END SP_CONSULTAR_DEPARTAMENTOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_CONSULTAR_EMPLEADOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_CONSULTAR_EMPLEADOS" (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT
            EmpleadoID,
            Nombre,
            PuestoID,
            DescripcionPuesto,
            DepartamentoID,
            DescripcionDepartamento
        FROM VW_EMPLEADOS
        ORDER BY EmpleadoID;
END SP_CONSULTAR_EMPLEADOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_CONSULTAR_PUESTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_CONSULTAR_PUESTOS" (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT PuestoID, Descripcion
        FROM PUESTO
        ORDER BY PuestoID;
END SP_CONSULTAR_PUESTOS;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_ELIMINAR_EMPLEADO" (
    p_empleadoID IN EMPLEADO.EmpleadoID%TYPE,
    p_filas_afectadas OUT NUMBER
) AS
BEGIN
    DELETE FROM EMPLEADO
    WHERE EmpleadoID = p_empleadoID;

    p_filas_afectadas := SQL%ROWCOUNT;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_EMPLEADO;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "EMPLEADOS"."SP_INSERTAR_EMPLEADO" (
    p_nombre        IN  EMPLEADO.Nombre%TYPE,
    p_puestoID      IN  EMPLEADO.PuestoID%TYPE,
    p_departamentoID IN EMPLEADO.DepartamentoID%TYPE,
    p_empleadoID    OUT EMPLEADO.EmpleadoID%TYPE
) AS
BEGIN
    INSERT INTO EMPLEADO (Nombre, PuestoID, DepartamentoID)
    VALUES (p_nombre, p_puestoID, p_departamentoID)
    RETURNING EmpleadoID INTO p_empleadoID;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_INSERTAR_EMPLEADO;

/
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "EMPLEADOS"."EMPLEADO" MODIFY ("EMPLEADOID" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."EMPLEADO" MODIFY ("DEPARTAMENTOID" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."EMPLEADO" MODIFY ("PUESTOID" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."EMPLEADO" ADD PRIMARY KEY ("EMPLEADOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUESTO
--------------------------------------------------------

  ALTER TABLE "EMPLEADOS"."PUESTO" MODIFY ("PUESTOID" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."PUESTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."PUESTO" ADD PRIMARY KEY ("PUESTOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "EMPLEADOS"."DEPARTAMENTO" MODIFY ("DEPARTAMENTOID" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."DEPARTAMENTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EMPLEADOS"."DEPARTAMENTO" ADD PRIMARY KEY ("DEPARTAMENTOID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "EMPLEADOS"."EMPLEADO" ADD CONSTRAINT "FK_EMP_DEPTO" FOREIGN KEY ("DEPARTAMENTOID")
	  REFERENCES "EMPLEADOS"."DEPARTAMENTO" ("DEPARTAMENTOID") ENABLE;
  ALTER TABLE "EMPLEADOS"."EMPLEADO" ADD CONSTRAINT "FK_EMP_PUESTO" FOREIGN KEY ("PUESTOID")
	  REFERENCES "EMPLEADOS"."PUESTO" ("PUESTOID") ENABLE;
